fit=rpart(YPH~.,data=cnrm, method="anova",control = rpart.control(cp = 0.01))
printcp(fit)
plotcp(fit)
plot(fit, "T", branch=0.9, margin = 0.01, main="CART of YPH for VLP"); text(fit, use.n = TRUE, cex=0.8)
rsq.rpart(fit)
predict(fit, type = "vector")


par(mfrow=c(2,4))
fit=rpart(YPH~.,data=cnrm, method="anova",control = rpart.control(cp = 0.01))
plot(fit, "T", branch=0.7, margin = 0.05, main="A. CART of YPH for CNR"); text(fit, use.n = TRUE, cex=0.8)
fit=rpart(YPH~.,data=gudm, method="anova",control = rpart.control(cp = 0.01))
plot(fit, "T", branch=0.7, margin = 0.01, main="B. CART of YPH for GUD"); text(fit, use.n = TRUE, cex=0.8)
fit=rpart(YPH~.,data=kopm, method="anova",control = rpart.control(cp = 0.01))
plot(fit, "T", branch=0.7, margin = 0.01, main="C. CART of YPH for KOP"); text(fit, use.n = TRUE, cex=0.8)
fit=rpart(YPH~.,data=mepm, method="anova",control = rpart.control(cp = 0.01))
plot(fit, "T", branch=0.7, margin = 0.01, main="D. CART of YPH for MEP"); text(fit, use.n = TRUE, cex=0.8)
fit=rpart(YPH~.,data=mnrm, method="anova",control = rpart.control(cp = 0.01))
plot(fit, "T", branch=0.7, margin = 0.01, main="E. CART of YPH for MNR"); text(fit, use.n = TRUE, cex=0.8)
fit=rpart(YPH~.,data=vlpm, method="anova",control = rpart.control(cp = 0.01))
plot(fit, "T", branch=0.7, margin = 0.01, main="F. CART of YPH for VLP"); text(fit, use.n = TRUE, cex=0.8)
fit=rpart(YPH~.,data=vprm, method="anova",control = rpart.control(cp = 0.01))
plot(fit, "T", branch=0.7, margin = 0.01, main="G. CART of YPH for VPR"); text(fit, use.n = TRUE, cex=0.8)
