library(ggmap)
library(sp)
spatial=read.csv("Spatial.csv",T)
coords < - cbind(Longitude = as.numeric(as.character(spatial$Lon)), Latitude = as.numeric(as.character(spatial$Lat)))
yph< - SpatialPointsDataFrame(coords, spatial[, (13:14)], proj4string = CRS("+init=epsg:4326"))
plot(yph, pch = ".", col = "darkred")
map< - qmap('Valparai', zoom = 12, maptype = 'satellite')
#map< - qmap('Valparai', zoom = 12, maptype = 'trerrain')
#map< - qmap('Valparai', zoom = 12, maptype = 'hybrid')
map + geom_point(data = spatial, aes(x = Lon, y = Lat), color="red", size=2, alpha=0.5)
map + stat_density2d(aes(x = Lon, y = Lat, fill = ..level.., alpha = ..level..*2), size = 2, bins = 5, data = spatial, geom = "polygon") + scale_fill_gradient(low = "black", high = "red")
address < - "Valparai, India"
(addressll < - geocode(address))
map(address, zoom = 12, source = "stamen", maptype = "toner")
map + geom_point(data = spatial, aes(x = Lon, y = Lat, size = AvgStdev), color = "red") + theme(legend.position = "none")
